" set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
colorscheme nord

" visuals
set number
set cursorline

" indentation, tabs
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2
    

" search
set incsearch
set hlsearch
set ignorecase
set smartcase

filetype plugin indent on
syntax on
